### ISSUE TITLE
Blur causes frame lag site-wide

### ISSUE THREAD

**Issue by aquifolly** [jschenke488/prismlauncher.github.io#1]
tested in firefox, unsure about chromium-based browser

**Comment by aquifolly** [comment]
actually, not just that, but it makes the entire window laggy, when on the tab

**Comment by jschenke488** [comment]
The blur is likely going to be removed in the final design, but I assume this has something to do with your browser or device as I didn't have lag in any of the browsers or devices I tested with.

**Comment by aquifolly** [comment]
interesting

**Comment by jschenke488** [comment]
https://github.com/jschenke488/prismlauncher.github.io/commit/c20e54fb3663f3e3556fa812dffa3ca8c57a5a22 and https://github.com/jschenke488/prismlauncher.github.io/commit/364909be36e1f7722128f74183224d96c4cea9a6
